# CI to release the project for Linux, ( Windows, and MacOS is optional )
# The purpose of this action is to verify if the release builds are working or not.

name: Preview deployments

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false
      
      - name: Install dependencies
        run: | 
          poetry lock
          poetry install

      - name: Build package
        run: poetry build
      
      - name: Install build wheel - x86_64
        run: |
          pip install --force-reinstall dist/*.whl
          cd ~ && python -c 'import midstar'
